using System;

// Token: 0x020003A8 RID: 936
public static class SoaringKeys
{
	// Token: 0x04001170 RID: 4464
	public const string Error_BadRequesMessage = "{ \"error_message\" : \"Failed to generate connection request\"}";

	// Token: 0x04001171 RID: 4465
	public const string Error_NotInitializedMessage = "Soaring Is Not Initializes";

	// Token: 0x04001172 RID: 4466
	public const string Soaring_ErrorMessageKeys = "error_message";

	// Token: 0x04001173 RID: 4467
	public const string Soaring_ErrorCodeKeys = "error_code";

	// Token: 0x04001174 RID: 4468
	public const string Soaring_ActionKey = "action";

	// Token: 0x04001175 RID: 4469
	public const string Modules_Handshake_GetKeys_Key = "handshake_pt1";

	// Token: 0x04001176 RID: 4470
	public const string Modules_Handshake_TestKeys_Key = "handshake_pt2";

	// Token: 0x04001177 RID: 4471
	public const string Modules_Handshake_FinishKeys_Key = "handshake_pt3";

	// Token: 0x04001178 RID: 4472
	public const string Modules_LoginUserKey = "loginUser";

	// Token: 0x04001179 RID: 4473
	public const string Modules_LookupUserKey = "lookupUser";

	// Token: 0x0400117A RID: 4474
	public const string Modules_RegisterUserKey = "registerUser";

	// Token: 0x0400117B RID: 4475
	public const string Modules_GenerateUserKey = "retrieveNextAutogeneratedUserTag";

	// Token: 0x0400117C RID: 4476
	public const string Modules_UpdateProfileKey = "updateUserProfile";

	// Token: 0x0400117D RID: 4477
	public const string Modules_GenerateInviteKey = "retrieveInvitationCode";

	// Token: 0x0400117E RID: 4478
	public const string Modules_AdServerKey = "adServer";

	// Token: 0x0400117F RID: 4479
	public const string Modules_RegisterDevice = "registerDevice";

	// Token: 0x04001180 RID: 4480
	public const string Modules_RetrieveUserProfile = "retrieveUserProfile";

	// Token: 0x04001181 RID: 4481
	public const string Modules_UpdateUserProfileKey = "updateUserProfile";

	// Token: 0x04001182 RID: 4482
	public const string Modules_ApplyInviteCodeKey = "applyInvitationCode";

	// Token: 0x04001183 RID: 4483
	public const string Modules_SearchFriendKey = "searchUsers";

	// Token: 0x04001184 RID: 4484
	public const string Modules_RequestFriendKey = "requestFriendship";

	// Token: 0x04001185 RID: 4485
	public const string Modules_RemoveFriendKey = "removeFriendship";

	// Token: 0x04001186 RID: 4486
	public const string Modules_SendSessionDataKey = "saveGameSession";

	// Token: 0x04001187 RID: 4487
	public const string Modules_RetrieveSessionDataKey = "retrieveGameSession";

	// Token: 0x04001188 RID: 4488
	public const string Modules_RetrieveFriendListKey = "retrieveFriendsList";

	// Token: 0x04001189 RID: 4489
	public const string Modules_CheckRewardsKey = "retrieveVirtualGoodCoupons";

	// Token: 0x0400118A RID: 4490
	public const string Modules_RedeemRewardsKey = "tearVirtualGoodCoupons";

	// Token: 0x0400118B RID: 4491
	public const string Modules_ServerTimeKey = "retrieveServerTime";

	// Token: 0x0400118C RID: 4492
	public const string Modules_VerifyRecieptKey = "validateIapReceipt";

	// Token: 0x0400118D RID: 4493
	public const string Modules_RetrievePurchasesKey = "retrieveIapPurchases";

	// Token: 0x0400118E RID: 4494
	public const string Modules_SendMessagesKey = "sendMessage";

	// Token: 0x0400118F RID: 4495
	public const string Modules_RetrieveMessagesKey = "retrieveUnreadMessages";

	// Token: 0x04001190 RID: 4496
	public const string Modules_MarkMessageReadKey = "markMessagesAsRead";

	// Token: 0x04001191 RID: 4497
	public const string Modules_ResetUserPasswordKey = "resetUserPassword";

	// Token: 0x04001192 RID: 4498
	public const string Modules_RenewUserPasswordKey = "renewUserPassword";

	// Token: 0x04001193 RID: 4499
	public const string Modules_RequestFriendWithTagKey = "requestFriendshipWithTag";

	// Token: 0x04001194 RID: 4500
	public const string Modules_RemoveFriendWithTagKey = "removeFriendshipWithTag";

	// Token: 0x04001195 RID: 4501
	public const string Modules_RetrieveAddressesKey = "retrieveGameLinks";

	// Token: 0x04001196 RID: 4502
	public const string Modules_RetrieveVersionsKey = "retrieveVersions";

	// Token: 0x04001197 RID: 4503
	public const string Modules_DownloadFileKey = "downloadFiles";

	// Token: 0x04001198 RID: 4504
	public const string Modules_ChangeUserPasswordKey = "changeUserPassword";

	// Token: 0x04001199 RID: 4505
	public const string Modules_RetrieveProductsKey = "retrieveIapProducts";

	// Token: 0x0400119A RID: 4506
	public const string Modules_SaveStatKey = "saveStat";

	// Token: 0x0400119B RID: 4507
	public const string Modules_SaveAnonymousStatKey = "saveAnonymousStat";

	// Token: 0x0400119C RID: 4508
	public const string Modules_RetrieveABCampaignKey = "retrieveABCampaignData";

	// Token: 0x0400119D RID: 4509
	public const string Modules_FireEventKey = "fireEvent";

	// Token: 0x0400119E RID: 4510
	public const string Soaring_UserAuthTokenKey = "authToken";

	// Token: 0x0400119F RID: 4511
	public const string Soaring_GameCenterIDKey = "gamecenterId";

	// Token: 0x040011A0 RID: 4512
	public const string Soaring_AmazonIDKey = "amazonId";

	// Token: 0x040011A1 RID: 4513
	public const string Soaring_GoogleIDKey = "googleId";

	// Token: 0x040011A2 RID: 4514
	public const string Soaring_FacebookIDKey = "facebookId";

	// Token: 0x040011A3 RID: 4515
	public const string Soaring_LoginTypeKey = "loginType";

	// Token: 0x040011A4 RID: 4516
	public const string Soaring_DeviceIDKey = "deviceId";

	// Token: 0x040011A5 RID: 4517
	public const string Soaring_NameKey = "name";

	// Token: 0x040011A6 RID: 4518
	public const string Soaring_UserTagKey = "tag";

	// Token: 0x040011A7 RID: 4519
	public const string Soaring_UserIDKey = "userId";

	// Token: 0x040011A8 RID: 4520
	public const string Soaring_UserPasswordKey = "password";

	// Token: 0x040011A9 RID: 4521
	public const string Soaring_UserAutoCreated = "autoCreated";

	// Token: 0x040011AA RID: 4522
	public const string Soaring_UserEmailKey = "email";

	// Token: 0x040011AB RID: 4523
	public const string Soaring_UserEmailsKey = "emails";

	// Token: 0x040011AC RID: 4524
	public const string Soaring_GameIDKey = "gameId";

	// Token: 0x040011AD RID: 4525
	public const string Soaring_UserStatusKey = "status";

	// Token: 0x040011AE RID: 4526
	public const string Soaring_InvitationCodeKey = "invitationCode";

	// Token: 0x040011AF RID: 4527
	public const string Soaring_ResetTokenKey = "resetToken";

	// Token: 0x040011B0 RID: 4528
	public const string Soaring_OldPasswordKey = "oldPassword";

	// Token: 0x040011B1 RID: 4529
	public const string Soaring_NewPasswordKey = "newPassword";

	// Token: 0x040011B2 RID: 4530
	public const string Soaring_ScoreKey = "score";

	// Token: 0x040011B3 RID: 4531
	public const string Soaring_PictureUrlKey = "pictureUrl";

	// Token: 0x040011B4 RID: 4532
	public const string Soaring_IconKey = "icon";

	// Token: 0x040011B5 RID: 4533
	public const string Soaring_SessionTypeKey = "sessionType";

	// Token: 0x040011B6 RID: 4534
	public const string Soaring_QueryTypeKey = "queryType";

	// Token: 0x040011B7 RID: 4535
	public const string Soaring_CustomKey = "custom";

	// Token: 0x040011B8 RID: 4536
	public const string Soaring_PublicKey = "public";

	// Token: 0x040011B9 RID: 4537
	public const string Soaring_PrivateKey = "private";

	// Token: 0x040011BA RID: 4538
	public const string Soaring_QueryKey = "query";

	// Token: 0x040011BB RID: 4539
	public const string Soaring_CouponKey = "coupons";

	// Token: 0x040011BC RID: 4540
	public const string Soaring_SortKey = "sort";

	// Token: 0x040011BD RID: 4541
	public const string Soaring_TypeKey = "type";

	// Token: 0x040011BE RID: 4542
	public const string Soaring_ValueKey = "value";

	// Token: 0x040011BF RID: 4543
	public const string Soaring_MessagesKey = "messages";

	// Token: 0x040011C0 RID: 4544
	public const string Soaring_DataKey = "data";

	// Token: 0x040011C1 RID: 4545
	public const string Soaring_TimestampKey = "timestamp";

	// Token: 0x040011C2 RID: 4546
	public const string Soaring_DateTimeKey = "datetime";

	// Token: 0x040011C3 RID: 4547
	public const string Soaring_GameSessionIdKey = "gameSessionId";

	// Token: 0x040011C4 RID: 4548
	public const string Soaring_IdentifiersKey = "identifiers";

	// Token: 0x040011C5 RID: 4549
	public const string Soaring_TokenKey = "token";

	// Token: 0x040011C6 RID: 4550
	public const string Soaring_ProtocolKey = "protocol";

	// Token: 0x040011C7 RID: 4551
	public const string Soaring_PlatformKey = "platform";

	// Token: 0x040011C8 RID: 4552
	public const string Soaring_ProductIDKey = "productId";

	// Token: 0x040011C9 RID: 4553
	public const string Soaring_RecieptKey = "receipt";

	// Token: 0x040011CA RID: 4554
	public const string Soaring_LabelKey = "label";

	// Token: 0x040011CB RID: 4555
	public const string Soaring_InternalKey = "SCInternal";

	// Token: 0x040011CC RID: 4556
	public const string Transport_PostKey = "tposts";

	// Token: 0x040011CD RID: 4557
	public const string Transport_GetKey = "tgets";

	// Token: 0x040011CE RID: 4558
	public const string Transport_UrlKey = "turl";

	// Token: 0x040011CF RID: 4559
	public const string Transport_SaveKey = "tsave";

	// Token: 0x040011D0 RID: 4560
	public const string Transport_ChannelKey = "tchannel";

	// Token: 0x040011D1 RID: 4561
	public const string Transport_ObjectKey = "tobject";

	// Token: 0x040011D2 RID: 4562
	public const string Transport_CallbackKey = "tcallback";

	// Token: 0x040011D3 RID: 4563
	public const string Transport_VerifyCallbackKey = "tvcallback";

	// Token: 0x040011D4 RID: 4564
	public const string Transport_ContextKey = "tcontext";

	// Token: 0x040011D5 RID: 4565
	public const string Transport_TokenKey = "trToken";

	// Token: 0x040011D6 RID: 4566
	public const string Transport_IgnoreOffline = "trIOff";

	// Token: 0x040011D7 RID: 4567
	public const string Transport_InternalRegister = "tregister";

	// Token: 0x040011D8 RID: 4568
	public const string SoaringSort_Descending = "descending";

	// Token: 0x040011D9 RID: 4569
	public const string SoaringSort_Ascending = "ascending";

	// Token: 0x040011DA RID: 4570
	public const string Soaring_GUIDKey = "guid";

	// Token: 0x040011DB RID: 4571
	public const string Soaring_DeviceGUIDKey = "device_seq_id";

	// Token: 0x040011DC RID: 4572
	public const string Soaring_DeviceSequenceIDKey = "device_seq_num";

	// Token: 0x040011DD RID: 4573
	public const string Soaring_EventNameKey = "event_name";

	// Token: 0x040011DE RID: 4574
	public const string Soaring_EventTimeKey = "event_time";

	// Token: 0x040011DF RID: 4575
	public const string Soaring_OSVersionKey = "os_version";

	// Token: 0x040011E0 RID: 4576
	public const string Soaring_OfflineKey = "Offline";
}
